---
title: "Data Source"
output: html_notebook
---
# SMS, Call, and Internet Data  
Data collected for internet, phone calls, SMS, and Twitter data was provided by the Telecom Italia Big Data Challenge. The data was acquired and anonymized by Telecom Italia. The data originates from Milan and surrounding areas between 1 November 2013 and 31 December 2013.  
  
All interactions on the mobile network generate Call Detail Records (CDRs). These are acquired by the following parameters:  
- SMS Data  
    - CDR is generated for each SMS sent and recieved  
- Call Data  
    - CDR is generated for each call sent and recieved  
- Internet Access: CDR is generated for the following events:  
    - Internet connection is opened  
    - Internet Connection is closed  
    - Internet Connection is open and 15 minutes has passed since last CDR  
    - Internet Connection is open and 5 MB have been transferred since last CDR was generated  
  
After being collected, the data was rescaled for privacy reasons. The SMS and call data were scaled using the same factor, while internet data was scaled using a different factor.  
  
# Twitter Data  
Similarly to the SMS, Call, and Internet Data, geo-localised tweets were collected from the Big Data Challenge (same time and location). It is not indicated that any data rescaling was completed. The paper does not state that the Twitter data is "normalized," so it is assumed to be untouched.  
  
# Football Match Attendees  
Football match attendance was retrieved from the [Italian National Football League 'Serie A' official website](http://www.legaseriea.it/it/lega-calcio/regolamenti-e-documenti/dati-statistici-su-incassi-e-spettatori). The final three games attendance data was obtained from two online newspapers ([Calciomercato](http://www.calciomercato.com/news/inter-trapani-3-2-il-tabellino-919259), [Milan News 1](http://www.milannews.it/il-match/quasi-cinquantamila-spettatori-riempiono-san-siro-105483), and [Milan News 2](http://www.milannews.it/il-match/milan-ajax-superati-i-61mila-spettatori-a-san-siro-130840)).  
  
# Airport Data  
The airport data was retrieved from the [Linate Airport website](http://www.milanolinate-airport.com/it). This data is only available for the current date + 4 days, so the data collected was for Monday 5 May 2014 through 11 May 2014. The measures used for estimating each hour of passenger amounts was calculated by summing the number of flights departing in the next 2 hours and the number of flights arriving in the past hour.  